### ISSUE TITLE
Button is unclickable or page not found

### ISSUE THREAD

**Issue by pmanuel994** [paylike/plugin-prestashop-1.7#27] opened 2021-02-26 11:26 UTC
Hello,
If we try to use paylike, we cannot click on button pay with classic checkout and with the supercheckout it shows page not found, so with none of them aren t working.
Example website:
https://fekete-koi.com/

**Comment by ionutcalara** [comment] 2021-02-26 11:42
Hi @pmanuel994 in the example the checkout isn't standard, so that is probably the issue. Can you share the website with the standard checkout where you are encountering issues? 

For non standard checkouts, we're open to making these compatible as long as the team behind that checkout has a guideline we can apply. However, we can't provide support for other third party plugins. We'd need them to make sure that their implementation does not break existing payment plugins.

**Comment by pmanuel994** [comment] 2021-02-26 11:44
Hi,
I have modified it now, please take a look again.
Thank you

**Comment by ionutcalara** [comment] 2021-02-26 11:49
In this particular case, the issue is due to the confirmation checkbox not being present. The plugin expects this: 
`#conditions-to-approve input[type="checkbox"]` to exist on the payment div and to be checked. When the user checks that, the button gets enabled.

**Comment by ionutcalara** [comment] 2021-03-17 06:07
As discussed on the other issue, supercheckout support will be available in the plugin. We do not have a timeline yet, but I will keep you updated. I am closing this issue. Feel free to reopen.

**Closed by ionutcalara** 2021-03-17 06:07 UTC
